spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_db
    username: root
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  server:
    port: 8080